name: Run Python Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install ipdb
          pip install setuptools
          pip install .
          pip install pytest-cov
      - name: Run tests with pytest
        run: pytest --cov=./ --cov-report=xml
      - name: Generate Report
        run: |
          pip install coverage
          #coverage run -m pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
